### ISSUE TITLE
Add a new release

### ISSUE THREAD

**Issue by skylarmacdonald** [piotrjaworski/primer-rails#4]
I probably ought to have done this in my PR if such a thing is possible, but it seems the latest commit needs to be tagged so GitHub will pick it up as a release, and then `gem` will install the right version.

Alternatively, I could just be doing it wrong.

**Comment by piotrjaworski** [comment]
Done!

**Comment by skylarmacdonald** [comment]
Thanks! I think you may also need to do a `gem push` to update it in RubyGems though, as it still doesn't seem to be picking it up 😬 I've used a GitHub source for now but would prefer to add `'~> 0.7.0'` to my Gemfile.

**Comment by piotrjaworski** [comment]
Sure, I've just pushed it :)
